### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by simonseddon** [tristandenyer/Clone-section-of-form-using-jQuery#4]
Label's don't seem to update their 'for' attributes to match the cloned/updated input id. On your example, the cloned labels, when clicked, check/focus the original input.

**Comment by tristandenyer** [comment]
You're right! Thanks for catching that. I tried a couple things, but they didn't work. Kind of tricky since I need the labels' 'for' and input's 'id' to match. So, I need to update them together. Only have a few mins to work on this, will need to try and tackle it later when I have more time. Will mark it as a TODO.  Thansk again!

**Comment by mms-hamburg** [comment]
any updates on this?

**Comment by tristandenyer** [comment]
I just checked and it looks like it does in fact match. When cloned, the the label's 'for' attribute reads the exact same as it's input id. I have no idea what made me think it didn't in my comment above, unless I am missing something now.

Clicking the labels in the demos that comes with the download also check/focus the appropriate inout field. Tabbing seems to work fine too.

Let me know if you find it to be not the case.

<img width="799" alt="screen shot 2015-07-22 at 2 39 36 pm" src="https://cloud.githubusercontent.com/assets/4358288/8838197/d1dc194c-307f-11e5-9f6d-d98ee3dcf73a.png">

**Comment by tristandenyer** [comment]
This is now fixed in the latest release! Let me know what you think.
